### ISSUE TITLE
Formating

### ISSUE THREAD

**Issue by mixMugz** [vatsimnetwork/simaware-tracon-project#117]
I can format the JSON in a nicer and more convenient way, and sort all the lines by id.

If it is necessary - merge all pull requests, I will do it within 15-30 minutes.

It is necessary in order not to affect other people's pull requests, the order of the lines will change.

![Screen Shot 2022-05-25 at 23 29 14](https://user-images.githubusercontent.com/17923916/170365340-0b5c0ea1-6821-4801-8eb4-2aa484af0f03.png)

**Comment by maiuswong** [comment]
sounds good, all pull requests have been closed.

**Comment by mixMugz** [comment]
> sounds good, all pull requests have been closed.

Ok. I going to format all stuff

**Comment by mixMugz** [comment]
https://github.com/maiuswong/simaware-tracon-project/pull/121
