### ISSUE TITLE
Question: Does DEP as well as APP have to be defined?

### ISSUE THREAD

**Issue by vatpacais** [vatsimnetwork/simaware-tracon-project#149]
The Readme states "When a callsign with a matching prefix/suffix pair is found, SimAware chooses the correct TRACON boundary to draw."

This implies that if a DEP position exists at the same airport with the same boundary  as the APP position, it has to be defined as well.

Is that correct? If so, wouldn't it be better to assume that if no suffix is defined, then either the _APP or _DEP callsign will active the boundary display? This should still allow for APP and DEP positions with different boundaries to be separately defined.

**Comment by maiuswong** [comment]
No - SimAware only looks at the prefix if the suffix isn't defined (or if the only defined suffix is APP).  

For example, M98 is currently defined with the prefix MSP and suffix APP.  For either case, either MSP_APP or MSP_DEP, the same polygon will light up.

The reason this exists is that certain sectors are defined by the APP/DEP suffix.  For example, LAX_DEP is a specific airspace (usually) just west of LAX.
