### ISSUE TITLE
Edit Callsign Label

### ISSUE THREAD

**Issue by githubvatsim** [vatsimnetwork/simaware-tracon-project#150]
The new callsign CZEG_APP is "Calgary-Edmonton Arrival". It is currently labelled "Calgary Approach/Departure" in Vatspy, I assume because it piggybacks on the CYYC_APP sector coordinates. Can this be edited?

(Separately, in Canada the _APP callsign is referred to as Arrival rather than Approach.)

**Comment by czeg-fc** [comment]
I have boundaries for this callsign.
[CZEG_APP.zip](https://github.com/vatsimnetwork/simaware-tracon-project/files/10301394/CZEG_APP.zip)

**Comment by Soofushka** [comment]
I suggest you to close Issue as i guess its already not actual
