### ISSUE TITLE
Overlap between multiple VATMEX/VATUSA TRACONs

### ISSUE THREAD

**Issue by dirtyformal** [vatsimnetwork/simaware-tracon-project#164]
With the addition of the VATMEX TMAs, it's now evident that there is a significant overlap between some TMAs. I have confirmed with VATMEX that all of their airspace is correct.

For example -

### MMML and NYL

![MMMLNYL](https://user-images.githubusercontent.com/13634684/189015077-09121afb-b7d8-465a-9df4-4761e22b8d9b.png)

### MMCS and ELP

![MMCSELP](https://user-images.githubusercontent.com/13634684/189015166-759d7ff0-73df-43ab-877e-d42eeb7d39bd.png)

### MMRX and VRA

![MMRXVRA](https://user-images.githubusercontent.com/13634684/189015244-1a919d56-f80d-4a89-9182-3dadf5884e98.png)

Additionally, some sectors such as U90, SCT and DLF need to be updated to align them with the border of the higher level airspace.

**Comment by abusivemilk** [comment]
I'm fixing NYL in a Pull Request right now.

With the data from the NAS, here's what it shows for the ELP/MMCS overlap and the Valley/MMRX/MMMA overlap (Mexico TMAs are as published, US TRACONs are pulled from both current ERAM files and the NAS.

I'm guessing this is all just LOA airspace or someone at the FAA just didn't want to be specific..

![image](https://user-images.githubusercontent.com/36498248/189514479-2fef0bfa-6bf1-4655-b271-5a3959f9d58d.png)

![image](https://user-images.githubusercontent.com/36498248/189514482-a10d78d6-9e25-455e-ac01-e0155542901a.png)

(Yellow is pulled from the NAS, Pink(? - colorblind) is what it's been updated to to match the MMML airspace.
![image](https://user-images.githubusercontent.com/36498248/189514489-937352e5-aaeb-4034-8622-d1a87c8051f7.png)

**Comment by abusivemilk** [comment]
Also, for fun, here's what it says the En-Route airspace is by ELP

![image](https://user-images.githubusercontent.com/36498248/189514608-044f3940-ff55-451e-ad97-93f1334cd0f4.png)

**Comment by dirtyformal** [comment]
Linked PR: #173 

Thanks for looking into this for me - I really appreciate it! Moving house at the moment, so my time is a little bit everywhere at the moment.

Appreciate the PR for this. I've approved it, and Karl will merge it in when he has time. Thanks again!
