### ISSUE TITLE
CTR Boundaries

### ISSUE THREAD

**Issue by sanek1000804** [vatsimnetwork/simaware-tracon-project#166]
Hello. One of the Russian regions often uses CTR's sectorization, so boundary on SimAware isn't always actual. Are you going to add the ability to adjust the borders of the CTR zones depending on the callsigns someday?

Also, I see that on map there are already correct boundaries (lines like this). So, it seems, map have already had all this boundaries and it remains only to bind them to the corresponding callsigns.
![image](https://user-images.githubusercontent.com/104563969/189466915-0718daaf-c6e2-4056-99a0-e9c4270e470b.png)

**Comment by sanek1000804** [comment]
Also, I see that on map there are already correct boundaries (lines like this). So, it seems, map have already had all this boundariesand and it remains only to bind them to the corresponding callsigns.
![image](https://user-images.githubusercontent.com/104563969/189376239-c8e7e3bf-ecc6-4dff-aff1-a176837fcbf9.png)

**Comment by dirtyformal** [comment]
Hey there, cheers for your query.

This specific project only deals with TRACON/Approach units, with Enroute positions being managed by the [VATSpy Data Project](https://github.com/vatsimnetwork/vatspy-data-project).

If I understand you correctly, you're meaning that you use the `_CTR` callsign for Approach/Departure units in some areas? If so, then unfortunately this would fall under the other VATSpy data project, as that is where that specific data is sourced from.

**Comment by sanek1000804** [comment]
No, I'm talking only about _CTR Boundaries, which aren't connected with approach/departure. So, for editing _CTR Boundaries, I need to contact VATSpy Data Project, right? And one more thing, if I will add correct _CTR Boundaries to VATSpy will they also appear on SimAware map?

**Comment by sanek1000804** [comment]
> Hey there, cheers for your query.
> 
> This specific project only deals with TRACON/Approach units, with Enroute positions being managed by the [VATSpy Data Project](https://github.com/vatsimnetwork/vatspy-data-project).
> 
> If I understand you correctly, you're meaning that you use the `_CTR` callsign for Approach/Departure units in some areas? If so, then unfortunately this would fall under the other VATSpy data project, as that is where that specific data is sourced from.

No, I'm talking only about _CTR Boundaries, which aren't connected with approach/departure. So, for editing _CTR Boundaries, I need to contact VATSpy Data Project, right? And one more thing, if I will add correct _CTR Boundaries to VATSpy will they also appear on SimAware map?

**Comment by sanek1000804** [comment]
> Okay cool. That's correct then - for _CTR sectors you'll need to jump across to the other project.
> 
> > if I will add correct _CTR Boundaries to VATSpy will they also appear on SimAware map?
> 
> Yes, they will carry over into the SimAware app.

Ok. Thank for reply.
