### ISSUE TITLE
Make nakhchivan active sector ( UBBA_CTR )

### ISSUE THREAD

**Issue by Atsamazz** [vatsimnetwork/simaware-tracon-project#230]
When you are connected as UBBA_CTR, Nakhchivan must be active sector. 

![Inkedchrome_DyzDUJZxCL](https://user-images.githubusercontent.com/106276857/196228062-93f8ee25-2ba1-469e-b8ff-9c30781bbcdd.jpg)

**Comment by maiuswong** [comment]
You will need to make a pull request in vatspy-data-project - this is only for TRACON boundaries.

**Comment by Atsamazz** [comment]
> You will need to make a pull request in vatspy-data-project - this is only for TRACON boundaries.

Roger
