### ISSUE TITLE
File name

### ISSUE THREAD

**Issue by NelisV** [vatsimnetwork/simaware-tracon-project#29]
https://github.com/maiuswong/simaware-tracon-project/blob/166ce4e2f9e4214706077e6a5ba05173f94b630d/TRACONBoundaries.geojson?short_path=9514027#L3

You probably want to change this.

**Comment by maiuswong** [comment]
literally just copypasta'd it from vatspy-data-project.  does it have any purpose or can it just be removed?

**Comment by NelisV** [comment]
It's a title for the dataset, can be anything you want.
