### ISSUE TITLE
No app/dep showing!

### ISSUE THREAD

**Issue by Lauvaan** [vatsimnetwork/simaware-tracon-project#290]
There is currenlty no app/dep controllers showing online in Simaware, even though those controllers are online.

**Comment by Lauvaan** [comment]
Now it works again!

**Comment by Lauvaan** [comment]
Works again!

**Comment by maiuswong** [comment]
Yes, but it is a band-aid.  I reverted SimAware to use v1.0.1 and it seems to have fixed it, meaning something in v1.0.2 is breaking it.

**Comment by maiuswong** [comment]
Seems like it was just a corrupted file that caused this issue.
