### ISSUE TITLE
Pull requests failures

### ISSUE THREAD

**Issue by sanek1000804** [vatsimnetwork/simaware-tracon-project#295]
![image](https://user-images.githubusercontent.com/104563969/226186457-7d351472-d1e9-49ad-9548-e36bfc49dfcb.png)
Last 4 pull requests have failure marks. What does it mean? I try to check using console at simaware website and it seems there is no SIP_APP boundary for example.
![image](https://user-images.githubusercontent.com/104563969/226186710-3dd45b90-cc87-4abd-88b4-9a10a5e6bd34.png)

**Comment by sanek1000804** [comment]
UTTT_APP also doesn't work
![image](https://user-images.githubusercontent.com/104563969/226690921-28501c3d-6ade-461c-a438-63ab8a3d1ae7.png)

**Comment by justinshannon** [comment]
The UTTT geoJSON file is not named correctly. It must end with `.json` … `UTTT.json`

**Comment by sanek1000804** [comment]
> The UTTT geoJSON file is not named correctly. It must end with `.json` … `UTTT.json`

Thank you very much! Will correct this.
