### ISSUE TITLE
Malformed multipolygons: do NOT have the same first and last coordinates, OR with initial coordinate repeated within coordinate list

### ISSUE THREAD

**Issue by jhchou** [vatsimnetwork/simaware-tracon-project#299]
For a `geojson` multipolygon, I believe the first and last points must be identical to form a proper "closed" shape.

However, there are multiple instances of multipolygons that do NOT close properly, causing code failure: e.g.

`IllegalArgumentException: Points of LinearRing do not form a closed linestring`.

Appending a copy of the first coordinate to the end of the multipolygon definition fixes this issue. Examples of entries with "open" multipolygons causing problems include:

```
# Non-closed
# 37 {"id":"BOI","prefix":["BOI"],"name":"Big Sky Approach"},"geometry":
# 46 {"id":"CHS","prefix":["CHS"],"name":"Charleston Approach"},"geometry":
# 90 {"id":"DNA","prefix":["DNA"],"name":"Da Nang Control"},"geometry":
# 94 {"id":"EBBR","prefix":["EBBR"],"name":"Brussels Arrival"},"geometry":
# 95 {"id":"EBCI","prefix":["EBCI"],"name":"Charleroi Approach"},"geometry":
```

When I thought this was a rare issue, I started manually fixing the polygons of my own personal download one at a time using a text editor, as I'm not that skilled a coder, but there seem to be a LOT of these.

I was wondering if anyone might be able to write a script to automatically detect and fix ALL of the problematic multipolygons all at once, so that EVERYONE could benefit from the fix?

**Comment by jhchou** [comment]
> `IllegalArgumentException: Points of LinearRing do not form a closed linestring`.

I have discovered a different class of invalid multipolygon definitions in the dataset.

In addition to the lack of a "closing" coordinate that matches the "initial" coordinate, there are 12 rows where the initial coordinate is found INTERIOR to the multipolygon coordinate list. My guess (without having plotted it out) is that this might be 2 separate polygons that connect at a single vertex?

The following are the malformed multipolygons:

```
# The following have the INITIAL coordinate also in the interior of the coordinate list
# 55: Ottawa & Quebec Terminals
# 403: Nadi Approach
# 687: Brisbane Approach Gold Coast
# 688: Brisbane Approach North
# 689: Brisbane Approach (North)
# 698: Melbourne Departures South
# 699: Melbourne Approach East
# 700: Melbourne Departures (South)
# 706: Perth Approach
# 710: Canberra Approach East
# 712: Nowra Approach
# 715: Williamtown Approach
```

**Comment by dirtyformal** [comment]
@codepip55 - Might be one for you to check out for the Australian TMR sectors.

**Comment by codepip55** [comment]
Hey Joe,

I recall you asking this in the past. You can read the discussion [here](https://discord.com/channels/775552633918062643/998691463284133908/1101450746005815326). Should you need any more clarification, feel free to reach out to me.
