### ISSUE TITLE
Budapest Approach TMA (LHBP_APP) Inverted latitude and longitude causing tracon boundary to appear over KSA.

### ISSUE THREAD

**Issue by Nestirium** [vatsimnetwork/simaware-tracon-project#311]
![image](https://github.com/vatsimnetwork/simaware-tracon-project/assets/65426814/dce6a5fd-137a-45d8-876a-ea7075317dfd)

**Comment by dirtyformal** [comment]
@bozibence - Looks like the TMA you've added is faulting. Please submit a fix!

**Comment by dirtyformal** [comment]
Fault is being discussed in closed PR #305. Discussion should continue here.
