### ISSUE TITLE
TMAs within LRBB/LUUU FIR

### ISSUE THREAD

**Issue by tgpetrica** [vatsimnetwork/simaware-tracon-project#325]
Hello, 
Yes, there are 4 TMAs in LRBB and 1 TMA in LUUU. (LRBB and LUUU being controlled by vACC Romania,) We are going to add all of them in the next PRs.

- LROP TMA (Bucharest) #324 
- LRCL TMA (NAPOC) #326 
- LRAR TMA (ARAD) #327 
- LRCK TMA (Constanta) #328 
- LUKK TMA (Chisinau) #329 

_Originally posted by @dirtyformal in https://github.com/vatsimnetwork/simaware-tracon-project/pull/324#pullrequestreview-1613036938_

**Comment by tgpetrica** [comment]
Hello @dirtyformal ,
I added all TMAs within LRBB (Bucharest FIR) and LUUU (Chisinau FIR). If all data is good, we are looking further to see Romanian airspace with new eyes.

Regards,
Teodor G Petrică
PR, VATSIM ROMANIA

**Comment by dirtyformal** [comment]
Thanks! I'll have a review of it when I finish up at work.

**Comment by dirtyformal** [comment]
Perfect, I've reviewed all of them, and Karl will also review and merge! Closing.
