### ISSUE TITLE
HND_TWR Does Not Appear

### ISSUE THREAD

**Issue by zladatm** [vatsimnetwork/simaware-tracon-project#334]
The ATIS does, though. It's also missing from VAT-Spy and Vattastic, which is odd. The airport is in the VAT-Spy database for certain.

**Comment by zladatm** [comment]
Turns out it is showing up as Tokyo Haneda....
![image](https://github.com/vatsimnetwork/simaware-tracon-project/assets/123500703/09e94078-c9d2-4b6f-9207-63c18b35e60b)

**Comment by dirtyformal** [comment]
Hi there @zladatm, as this is an issue with the Simaware tool itself, please open an issue on their GitHub page - [found here](https://github.com/maiuswong/simaware-express).

This repository only handles the lateral boundaries of the TMA/TRACON sectors. Closing.
