### ISSUE TITLE
Any 199.998 Freq should not be displayed.

### ISSUE THREAD

**Issue by kye-taylor** [vatsimnetwork/simaware-tracon-project#339]
![image](https://github.com/vatsimnetwork/simaware-tracon-project/assets/46931474/a40b2cef-fe98-49fa-bc05-946494312a55)

199.998 are unprimed, not active ATC and should not be displayed on any sector

**Comment by dirtyformal** [comment]
Hi there @kye-taylor, as this is an issue with the Simaware tool itself, please open an issue on their GitHub page - [found here](https://github.com/maiuswong/simaware-express).

This repository only handles the lateral boundaries of the TMA/TRACON sectors. Closing.
