### ISSUE TITLE
Tag does not close

### ISSUE THREAD

**Issue by MatisseBE** [vatsimnetwork/simaware-tracon-project#349]
When selecting one aircraft, and directly afterwards you select another aircraft, the tag of the first aircraft does not close. 
![image](https://github.com/vatsimnetwork/simaware-tracon-project/assets/51272243/3698cb42-d75b-4e44-a52b-7c043cf13ef9)

I expect this to not be the intended behavior since there is no way to keep the tag displayed in any other way.
The tag can be closed again after clicking the aircraft again.

**Comment by maiuswong** [comment]
not the correct repo to post simaware issues.
