### ISSUE TITLE
Possibility change colors of aircrafts

### ISSUE THREAD

**Issue by Waltervizzi** [vatsimnetwork/simaware-tracon-project#360]
Hi guys ,
It would be nice to be able to change the color of the planes because when using satellite mode the green colored planes blend in with the ground Could it be possible to change the color?

**Comment by marcelobarretto** [comment]
This request is probably better suited for the Simaware repository https://github.com/maiuswong/simaware-express/issues.

**Comment by dirtyformal** [comment]
Hi @Waltervizzi. As @marcelobarretto correctly stated - your request would be better handled by the SimAware platform repository, [which can be found here](https://github.com/maiuswong/simaware-express/).

This repository is for the data that is ingested in various locations around the VATSIM network for TMA locations. Whereas the SimAware repository is for that explicit tool - of which the display of the plane icons falls under. Please open an issue with that repository,

Closing.
