### ISSUE TITLE
Seattle Tracon (S46)

### ISSUE THREAD

**Issue by GunGuyAlex** [vatsimnetwork/simaware-tracon-project#73]
S46 is missing the northern part above KPAE

![Simaware S46 missing over PAE](https://user-images.githubusercontent.com/100453092/155824181-15fe1323-e321-44fd-abd4-dbbe3ce8709f.png)
![vSTARS Top S46](https://user-images.githubusercontent.com/100453092/155824199-e59a4530-224e-4ea0-8434-a7cfc7108582.png)

**Comment by kmoberg** [comment]
ZSE FE has been informed that they need to submit an update if this is still an issue.
